export enum DataKey {
  HUE_V1_HUB = 'HUE_V1_HUB',
  HUE_V1_USERNAME = 'HUE_V1_USERNAME',
  HUE_V1_LIGHTS = 'HUE_V1_LIGHT',
  HUE_HUB = 'HUE_HUB',
  HUE_USERNAME = 'HUE_USERNAME',
  HUE_LIGHTS = 'HUE_USERNAME',
}
